# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Coding\RailwayInfoSys\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 761, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_user = QtWidgets.QWidget()
        self.tab_user.setObjectName("tab_user")
        self.list_user = QtWidgets.QListWidget(self.tab_user)
        self.list_user.setGeometry(QtCore.QRect(10, 50, 261, 471))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list_user.setFont(font)
        self.list_user.setObjectName("list_user")
        self.label = QtWidgets.QLabel(self.tab_user)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.tab_user)
        self.groupBox.setGeometry(QtCore.QRect(280, 20, 461, 501))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 61, 21))
        self.label_2.setObjectName("label_2")
        self.lineedit_user_uid = QtWidgets.QLineEdit(self.groupBox)
        self.lineedit_user_uid.setGeometry(QtCore.QRect(40, 60, 321, 31))
        self.lineedit_user_uid.setText("")
        self.lineedit_user_uid.setFrame(True)
        self.lineedit_user_uid.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_user_uid.setReadOnly(True)
        self.lineedit_user_uid.setObjectName("lineedit_user_uid")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.label_3.setObjectName("label_3")
        self.lineedit_user_name = QtWidgets.QLineEdit(self.groupBox)
        self.lineedit_user_name.setGeometry(QtCore.QRect(40, 130, 321, 31))
        self.lineedit_user_name.setText("")
        self.lineedit_user_name.setFrame(True)
        self.lineedit_user_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_user_name.setReadOnly(False)
        self.lineedit_user_name.setObjectName("lineedit_user_name")
        self.lineedit_user_password = QtWidgets.QLineEdit(self.groupBox)
        self.lineedit_user_password.setGeometry(QtCore.QRect(40, 200, 321, 31))
        self.lineedit_user_password.setText("")
        self.lineedit_user_password.setFrame(True)
        self.lineedit_user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineedit_user_password.setReadOnly(False)
        self.lineedit_user_password.setObjectName("lineedit_user_password")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 61, 21))
        self.label_4.setObjectName("label_4")
        self.button_user_edit = QtWidgets.QPushButton(self.groupBox)
        self.button_user_edit.setGeometry(QtCore.QRect(70, 320, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_user_edit.setFont(font)
        self.button_user_edit.setObjectName("button_user_edit")
        self.button_user_del = QtWidgets.QPushButton(self.groupBox)
        self.button_user_del.setGeometry(QtCore.QRect(170, 390, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_user_del.setFont(font)
        self.button_user_del.setObjectName("button_user_del")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(30, 240, 71, 21))
        self.label_22.setObjectName("label_22")
        self.spin_user_level = QtWidgets.QSpinBox(self.groupBox)
        self.spin_user_level.setGeometry(QtCore.QRect(40, 260, 321, 31))
        self.spin_user_level.setMaximum(2)
        self.spin_user_level.setProperty("value", 2)
        self.spin_user_level.setObjectName("spin_user_level")
        self.button_user_add = QtWidgets.QPushButton(self.groupBox)
        self.button_user_add.setGeometry(QtCore.QRect(230, 320, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_user_add.setFont(font)
        self.button_user_add.setObjectName("button_user_add")
        self.tabWidget.addTab(self.tab_user, "")
        self.tab_station = QtWidgets.QWidget()
        self.tab_station.setObjectName("tab_station")
        self.list_station_list = QtWidgets.QListWidget(self.tab_station)
        self.list_station_list.setGeometry(QtCore.QRect(10, 50, 261, 471))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list_station_list.setFont(font)
        self.list_station_list.setObjectName("list_station_list")
        self.label_5 = QtWidgets.QLabel(self.tab_station)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_station)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 20, 461, 501))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 61, 21))
        self.label_6.setObjectName("label_6")
        self.lineedit_station_code = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineedit_station_code.setGeometry(QtCore.QRect(40, 60, 321, 31))
        self.lineedit_station_code.setText("")
        self.lineedit_station_code.setFrame(True)
        self.lineedit_station_code.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_station_code.setReadOnly(False)
        self.lineedit_station_code.setObjectName("lineedit_station_code")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.label_7.setObjectName("label_7")
        self.lineedit_station_name = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineedit_station_name.setGeometry(QtCore.QRect(40, 130, 321, 31))
        self.lineedit_station_name.setText("")
        self.lineedit_station_name.setFrame(True)
        self.lineedit_station_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineedit_station_name.setReadOnly(False)
        self.lineedit_station_name.setObjectName("lineedit_station_name")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 61, 21))
        self.label_8.setObjectName("label_8")
        self.button_station_edit = QtWidgets.QPushButton(self.groupBox_2)
        self.button_station_edit.setGeometry(QtCore.QRect(80, 260, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_station_edit.setFont(font)
        self.button_station_edit.setObjectName("button_station_edit")
        self.button_station_del = QtWidgets.QPushButton(self.groupBox_2)
        self.button_station_del.setGeometry(QtCore.QRect(170, 330, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_station_del.setFont(font)
        self.button_station_del.setObjectName("button_station_del")
        self.button_station_add = QtWidgets.QPushButton(self.groupBox_2)
        self.button_station_add.setGeometry(QtCore.QRect(240, 260, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_station_add.setFont(font)
        self.button_station_add.setObjectName("button_station_add")
        self.spin_train_type = QtWidgets.QSpinBox(self.groupBox_2)
        self.spin_train_type.setGeometry(QtCore.QRect(40, 200, 321, 31))
        self.spin_train_type.setMaximum(1)
        self.spin_train_type.setObjectName("spin_train_type")
        self.tabWidget.addTab(self.tab_station, "")
        self.tab_line = QtWidgets.QWidget()
        self.tab_line.setObjectName("tab_line")
        self.table_line = QtWidgets.QTableWidget(self.tab_line)
        self.table_line.setGeometry(QtCore.QRect(10, 40, 731, 281))
        self.table_line.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_line.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_line.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_line.setObjectName("table_line")
        self.table_line.setColumnCount(5)
        self.table_line.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_line.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_line.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_line.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_line.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_line.setHorizontalHeaderItem(4, item)
        self.table_line.verticalHeader().setVisible(False)
        self.label_17 = QtWidgets.QLabel(self.tab_line)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_17.setObjectName("label_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_line)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 330, 731, 191))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(50, 50, 61, 31))
        self.label_18.setObjectName("label_18")
        self.combo_line_depart = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_line_depart.setGeometry(QtCore.QRect(110, 50, 171, 31))
        self.combo_line_depart.setObjectName("combo_line_depart")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(320, 50, 61, 31))
        self.label_19.setObjectName("label_19")
        self.combo_line_arrive = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_line_arrive.setGeometry(QtCore.QRect(380, 50, 171, 31))
        self.combo_line_arrive.setObjectName("combo_line_arrive")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(50, 110, 61, 31))
        self.label_20.setObjectName("label_20")
        self.spin_line_time = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_line_time.setGeometry(QtCore.QRect(110, 110, 111, 31))
        self.spin_line_time.setObjectName("spin_line_time")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(220, 110, 61, 31))
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(320, 110, 61, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(510, 110, 41, 31))
        self.label_27.setObjectName("label_27")
        self.spin_line_cost = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_line_cost.setGeometry(QtCore.QRect(380, 110, 131, 31))
        self.spin_line_cost.setObjectName("spin_line_cost")
        self.button_line_add = QtWidgets.QPushButton(self.groupBox_4)
        self.button_line_add.setGeometry(QtCore.QRect(600, 30, 91, 41))
        self.button_line_add.setObjectName("button_line_add")
        self.button_line_del = QtWidgets.QPushButton(self.groupBox_4)
        self.button_line_del.setGeometry(QtCore.QRect(600, 130, 91, 41))
        self.button_line_del.setObjectName("button_line_del")
        self.button_line_edit = QtWidgets.QPushButton(self.groupBox_4)
        self.button_line_edit.setGeometry(QtCore.QRect(600, 80, 91, 41))
        self.button_line_edit.setObjectName("button_line_edit")
        self.tabWidget.addTab(self.tab_line, "")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.label_9 = QtWidgets.QLabel(self.tab_train)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_9.setObjectName("label_9")
        self.table_train = QtWidgets.QTableWidget(self.tab_train)
        self.table_train.setGeometry(QtCore.QRect(10, 40, 731, 192))
        self.table_train.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_train.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_train.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_train.setObjectName("table_train")
        self.table_train.setColumnCount(11)
        self.table_train.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_train.setHorizontalHeaderItem(10, item)
        self.table_train.verticalHeader().setVisible(False)
        self.list_train_line = QtWidgets.QListWidget(self.tab_train)
        self.list_train_line.setGeometry(QtCore.QRect(10, 260, 256, 261))
        self.list_train_line.setObjectName("list_train_line")
        self.label_10 = QtWidgets.QLabel(self.tab_train)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 71, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_train)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 240, 461, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label_11.setObjectName("label_11")
        self.combo_tain_depart = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_tain_depart.setGeometry(QtCore.QRect(110, 100, 171, 20))
        self.combo_tain_depart.setObjectName("combo_tain_depart")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(30, 99, 71, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(30, 140, 61, 21))
        self.label_13.setObjectName("label_13")
        self.spin_train_carriage = QtWidgets.QSpinBox(self.groupBox_3)
        self.spin_train_carriage.setGeometry(QtCore.QRect(90, 140, 42, 22))
        self.spin_train_carriage.setObjectName("spin_train_carriage")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(150, 140, 61, 21))
        self.label_14.setObjectName("label_14")
        self.spin_train_first = QtWidgets.QSpinBox(self.groupBox_3)
        self.spin_train_first.setGeometry(QtCore.QRect(210, 140, 42, 22))
        self.spin_train_first.setObjectName("spin_train_first")
        self.spin_train_second = QtWidgets.QSpinBox(self.groupBox_3)
        self.spin_train_second.setGeometry(QtCore.QRect(340, 140, 42, 22))
        self.spin_train_second.setObjectName("spin_train_second")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(280, 140, 61, 21))
        self.label_15.setObjectName("label_15")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(10, 170, 441, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.button_train_addtrain = QtWidgets.QPushButton(self.groupBox_3)
        self.button_train_addtrain.setGeometry(QtCore.QRect(320, 60, 51, 51))
        self.button_train_addtrain.setObjectName("button_train_addtrain")
        self.combo_tain_line = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_tain_line.setGeometry(QtCore.QRect(110, 190, 171, 31))
        self.combo_tain_line.setObjectName("combo_tain_line")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(30, 190, 71, 31))
        self.label_16.setObjectName("label_16")
        self.button_train_addline = QtWidgets.QPushButton(self.groupBox_3)
        self.button_train_addline.setGeometry(QtCore.QRect(70, 230, 91, 41))
        self.button_train_addline.setObjectName("button_train_addline")
        self.button_train_delline = QtWidgets.QPushButton(self.groupBox_3)
        self.button_train_delline.setGeometry(QtCore.QRect(190, 230, 91, 41))
        self.button_train_delline.setObjectName("button_train_delline")
        self.button_train_saveline = QtWidgets.QPushButton(self.groupBox_3)
        self.button_train_saveline.setGeometry(QtCore.QRect(310, 230, 91, 41))
        self.button_train_saveline.setObjectName("button_train_saveline")
        self.button_train_deltrain = QtWidgets.QPushButton(self.groupBox_3)
        self.button_train_deltrain.setGeometry(QtCore.QRect(380, 60, 51, 51))
        self.button_train_deltrain.setObjectName("button_train_deltrain")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(30, 30, 71, 21))
        self.label_23.setObjectName("label_23")
        self.lineedit_train_code = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineedit_train_code.setGeometry(QtCore.QRect(110, 30, 171, 20))
        self.lineedit_train_code.setText("")
        self.lineedit_train_code.setObjectName("lineedit_train_code")
        self.time_train_depart = QtWidgets.QTimeEdit(self.groupBox_3)
        self.time_train_depart.setGeometry(QtCore.QRect(110, 60, 171, 22))
        self.time_train_depart.setObjectName("time_train_depart")
        self.tabWidget.addTab(self.tab_train, "")
        self.tab_ticket = QtWidgets.QWidget()
        self.tab_ticket.setObjectName("tab_ticket")
        self.label_24 = QtWidgets.QLabel(self.tab_ticket)
        self.label_24.setGeometry(QtCore.QRect(290, 20, 61, 31))
        self.label_24.setObjectName("label_24")
        self.combo_ticket_depart = QtWidgets.QComboBox(self.tab_ticket)
        self.combo_ticket_depart.setGeometry(QtCore.QRect(80, 20, 171, 31))
        self.combo_ticket_depart.setObjectName("combo_ticket_depart")
        self.label_25 = QtWidgets.QLabel(self.tab_ticket)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 61, 31))
        self.label_25.setObjectName("label_25")
        self.combo_ticket_arrive = QtWidgets.QComboBox(self.tab_ticket)
        self.combo_ticket_arrive.setGeometry(QtCore.QRect(350, 20, 171, 31))
        self.combo_ticket_arrive.setObjectName("combo_ticket_arrive")
        self.checkBox = QtWidgets.QCheckBox(self.tab_ticket)
        self.checkBox.setGeometry(QtCore.QRect(540, 20, 71, 31))
        self.checkBox.setObjectName("checkBox")
        self.table_ticket = QtWidgets.QTableWidget(self.tab_ticket)
        self.table_ticket.setGeometry(QtCore.QRect(20, 100, 721, 411))
        self.table_ticket.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_ticket.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_ticket.setObjectName("table_ticket")
        self.table_ticket.setColumnCount(8)
        self.table_ticket.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_ticket.setHorizontalHeaderItem(7, item)
        self.label_28 = QtWidgets.QLabel(self.tab_ticket)
        self.label_28.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_28.setObjectName("label_28")
        self.pushButton = QtWidgets.QPushButton(self.tab_ticket)
        self.pushButton.setGeometry(QtCore.QRect(620, 20, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_ticket, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.button_user_edit.clicked.connect(self.userEdit)
        self.button_user_del.clicked.connect(self.userDel)
        self.button_station_edit.clicked.connect(self.stationEdit)
        self.button_station_add.clicked.connect(self.stationAdd)
        self.button_station_del.clicked.connect(self.stationDel)
        self.button_train_addtrain.clicked.connect(self.trainAdd)
        self.button_train_addline.clicked.connect(self.trainLineadd)
        self.button_train_delline.clicked.connect(self.trainLinedel)
        self.button_train_saveline.clicked.connect(self.trainLinesave)
        self.list_user.itemClicked['QListWidgetItem*'].connect(self.userListre)
        self.list_station_list.itemClicked['QListWidgetItem*'].connect(self.stationListre)
        self.button_train_deltrain.clicked.connect(self.trainDel)
        self.button_line_add.clicked.connect(self.lineAdd)
        self.button_line_del.clicked.connect(self.lineDel)
        self.tabWidget.currentChanged['int'].connect(self.refreshAll)
        self.button_user_add.clicked.connect(self.userAdd)
        self.table_train.itemClicked['QTableWidgetItem*'].connect(self.trainTablere)
        self.list_train_line.itemClicked['QListWidgetItem*'].connect(self.trainListre)
        self.button_line_edit.clicked.connect(self.lineEdit)
        self.table_line.itemClicked['QTableWidgetItem*'].connect(self.lineTablere)
        self.pushButton.clicked.connect(self.ticketQuery)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "铁路信息查询系统"))
        self.label.setText(_translate("MainWindow", "用户列表："))
        self.groupBox.setTitle(_translate("MainWindow", "信息修改"))
        self.label_2.setText(_translate("MainWindow", "用户UID："))
        self.label_3.setText(_translate("MainWindow", "用户名："))
        self.label_4.setText(_translate("MainWindow", "密码："))
        self.button_user_edit.setText(_translate("MainWindow", "修改信息"))
        self.button_user_del.setText(_translate("MainWindow", "删除用户"))
        self.label_22.setText(_translate("MainWindow", "用户权限："))
        self.button_user_add.setText(_translate("MainWindow", "添加用户"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_user), _translate("MainWindow", "用户管理"))
        self.label_5.setText(_translate("MainWindow", "车站列表："))
        self.groupBox_2.setTitle(_translate("MainWindow", "信息修改"))
        self.label_6.setText(_translate("MainWindow", "车站代码："))
        self.label_7.setText(_translate("MainWindow", "车站名"))
        self.label_8.setText(_translate("MainWindow", "车站类型"))
        self.button_station_edit.setText(_translate("MainWindow", "修改信息"))
        self.button_station_del.setText(_translate("MainWindow", "删除车站"))
        self.button_station_add.setText(_translate("MainWindow", "添加车站"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_station), _translate("MainWindow", "车站信息管理"))
        item = self.table_line.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_line.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "始发站"))
        item = self.table_line.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "到达站"))
        item = self.table_line.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "时间"))
        item = self.table_line.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "费用"))
        self.label_17.setText(_translate("MainWindow", "线路列表："))
        self.groupBox_4.setTitle(_translate("MainWindow", "线路编辑"))
        self.label_18.setText(_translate("MainWindow", "始发站："))
        self.label_19.setText(_translate("MainWindow", "到达站："))
        self.label_20.setText(_translate("MainWindow", "时间："))
        self.label_21.setText(_translate("MainWindow", "（分钟）"))
        self.label_26.setText(_translate("MainWindow", "价格："))
        self.label_27.setText(_translate("MainWindow", "（元）"))
        self.button_line_add.setText(_translate("MainWindow", "添加线路"))
        self.button_line_del.setText(_translate("MainWindow", "删除线路"))
        self.button_line_edit.setText(_translate("MainWindow", "修改线路"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_line), _translate("MainWindow", "线路管理"))
        self.label_9.setText(_translate("MainWindow", "列车列表："))
        item = self.table_train.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_train.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "车次"))
        item = self.table_train.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "发车时间"))
        item = self.table_train.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "到达时间"))
        item = self.table_train.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "始发站"))
        item = self.table_train.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "终到站"))
        item = self.table_train.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "线路段数"))
        item = self.table_train.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "全程票价"))
        item = self.table_train.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "车厢数"))
        item = self.table_train.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "一等座"))
        item = self.table_train.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "二等座"))
        self.label_10.setText(_translate("MainWindow", "经过线路："))
        self.groupBox_3.setTitle(_translate("MainWindow", "列车/线路编辑"))
        self.label_11.setText(_translate("MainWindow", "发车时间："))
        self.label_12.setText(_translate("MainWindow", "始发站："))
        self.label_13.setText(_translate("MainWindow", "车厢数："))
        self.label_14.setText(_translate("MainWindow", "一等座："))
        self.label_15.setText(_translate("MainWindow", "二等座："))
        self.button_train_addtrain.setText(_translate("MainWindow", "添加\n"
"车辆"))
        self.label_16.setText(_translate("MainWindow", "线路选择："))
        self.button_train_addline.setText(_translate("MainWindow", "添加线路"))
        self.button_train_delline.setText(_translate("MainWindow", "删除线路"))
        self.button_train_saveline.setText(_translate("MainWindow", "保存更改"))
        self.button_train_deltrain.setText(_translate("MainWindow", "删除\n"
"车辆"))
        self.label_23.setText(_translate("MainWindow", "班次号："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_train), _translate("MainWindow", "列车管理"))
        self.label_24.setText(_translate("MainWindow", "到达站："))
        self.label_25.setText(_translate("MainWindow", "始发站："))
        self.checkBox.setText(_translate("MainWindow", "联程"))
        item = self.table_ticket.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "车次"))
        item = self.table_ticket.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "发车时间"))
        item = self.table_ticket.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "全程票价"))
        item = self.table_ticket.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "始发站"))
        item = self.table_ticket.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "终到站"))
        item = self.table_ticket.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "实际票价"))
        item = self.table_ticket.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "历时"))
        item = self.table_ticket.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "过路车"))
        self.label_28.setText(_translate("MainWindow", "搜索结果："))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ticket), _translate("MainWindow", "车票查询"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

